name: Merge Group Checks
on:
    merge_group:
        types: [checks_requested]
jobs:
    minimal-check:
        runs-on: ubuntu-latest
        steps:
            - name: Always pass
              run: echo "All good!"
